QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chômage', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 25 } } },
	judge = { label = 'D.O.J', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juge', payment = 100 } } },
	lawyer = { label = 'Cabinet d\'Avocat', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associé', payment = 50 } } },
	reporter = { label = 'Weazel News', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journaliste', payment = 30 } } },
	trucker = { label = 'Camionneur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 25 } } },
	tow = { label = 'Remorqueur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 25 } } },
	garbage = { label = 'Eboueur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collecteur', payment = 25 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vendeur', payment = 25 } } },

	police = {
		label = 'L.S.P.D',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Officier', payment = 75 },
			['2'] = { name = 'Sergent', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Capitaine', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 25 },
			['1'] = { name = 'Paramedic', payment = 40 },
			['2'] = { name = 'Docteur', payment = 60 },
			['3'] = { name = 'Chirurgien', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	realestate = {
		label = 'Agent Immobilier',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 25 },
			['1'] = { name = 'Courtier', payment = 40 },
			['2'] = { name = 'Représentant', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 25 },
			['1'] = { name = 'Chauffeur', payment = 40 },
			['2'] = { name = 'Chauffeur V.I.P', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	cardealer = {
		label = 'Concessionnaire',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 25 },
			['1'] = { name = 'Courtier', payment = 40 },
			['2'] = { name = 'Représentant', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	vineyard = {
		label = 'Vineyard',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprenti', payment = 25 },
			['1'] = { name = 'Cultivateur', payment = 40 },
			['2'] = { name = 'Chef de chai', payment = 60 },
			['3'] = { name = 'Manager', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	burgershot = {
		label = "Burgershot",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Apprenti", payment = 25 },
			['1'] = { name = "Cuisinier", payment = 40 },
			['2'] = { name = "Caissier", payment = 60 },
			['3'] = { name = "Manager", payment = 80 },
			['4'] = { name = "Patron", isboss = true, payment = 100 },
		}
	},
	cardealerjob = {
		label = 'Concessionnaire Véhicule Professionnel',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 25 },
			['1'] = { name = 'Courtier', payment = 40 },
			['2'] = { name = 'Représentant', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		}
	},
	mechanic = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécano Novice', payment = 40 },
			['2'] = { name = ' Mécano Expérimenté', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	lscustom = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécano Novice', payment = 40 },
			['2'] = { name = ' Mécano Expérimenté', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	lsharmony = {
		label = 'LS Harmony',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécano Novice', payment = 40 },
			['2'] = { name = ' Mécano Expérimenté', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécano Novice', payment = 40 },
			['2'] = { name = ' Mécano Expérimenté', payment = 60 },
			['3'] = { name = 'Assistant', payment = 80 },
			['4'] = { name = 'Patron', isboss = true, payment = 100 },
		},
	},
}
